# Generated by Django 3.2 on 2023-08-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_favorited_by'),
        ('accounts', '0002_alter_account_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='favorite_products',
            field=models.ManyToManyField(blank=True, related_name='favorite_products', to='shop.Product'),
        ),
    ]
