# Generated by Django 3.2 on 2023-08-15 04:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
