# Generated by Django 3.2 on 2023-08-18 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='shipping',
            options={'ordering': ['-bundle__delivery_date', '-status']},
        ),
        migrations.AddField(
            model_name='shipping',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shippings', to='shipping.deliverybundle'),
        ),
    ]
